/**
 * One tool list for the live viewport and the file-backed project.
 * HTTP bus routes by backend; agents only send name + JSON args.
 */

export type ToolBackend = 'live' | 'project';
export type ToolGroup = 'core' | 'observe' | 'dsl' | 'io' | 'device' | 'project';

export interface ToolAnnotations {
  readOnlyHint?: boolean;
  destructiveHint?: boolean;
  idempotentHint?: boolean;
  openWorldHint?: boolean;
}

export interface AgentTool {
  name: string;
  description: string;
  backend: ToolBackend;
  group: ToolGroup;
  annotations: ToolAnnotations;
  inputSchema: Record<string, unknown>;
}

const obj = (properties: Record<string, unknown>, required: string[] = []): Record<string, unknown> => ({
  type: 'object',
  additionalProperties: false,
  properties,
  required,
});

const vec3 = {
  type: 'object',
  additionalProperties: false,
  properties: {
    x: { type: 'number' },
    y: { type: 'number' },
    z: { type: 'number' },
  },
  required: ['x', 'y', 'z'],
};

const read = { readOnlyHint: true, destructiveHint: false, openWorldHint: false };
const write = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
const destroy = { readOnlyHint: false, destructiveHint: true, openWorldHint: false };
const world = { readOnlyHint: false, openWorldHint: true };

export const AGENT_TOOLS: AgentTool[] = [
  {
    name: 'scene.get',
    backend: 'live',
    group: 'core',
    annotations: read,
    description: 'Read live scene ids, transforms, timeline, cameras, paths. Structural data, not visual evidence. Call before edits.',
    inputSchema: obj({}),
  },
  {
    name: 'scene.edit',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Apply 1–50 operations as one undo step. Failure writes nothing. Ops include add_character, add_prop, set_pose, add_campath, set_campath, add_move_path, set_motion, add_anim_clip, set_environment (plus exposure/toneMap/dof/ibl/lut), set_camera, set_transform, set_part, rename, remove, add_coverage, add_angles, set_lens_combo, set_light_rig, add_light, set_look, set_look_at, plant_feet, plus set_relations / solve_layout.',
    inputSchema: obj({
      description: { type: 'string' },
      operations: { type: 'array', minItems: 1, maxItems: 50, items: { type: 'object' } },
      validateOnly: { type: 'boolean' },
    }, ['operations']),
  },
  {
    name: 'scene.history',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Undo or redo live scene edits.',
    inputSchema: obj({
      action: { type: 'string', enum: ['undo', 'redo'] },
      steps: { type: 'integer', minimum: 1, maximum: 20 },
    }, ['action']),
  },
  {
    name: 'scene.diagnostics',
    backend: 'live',
    group: 'observe',
    annotations: read,
    description: 'Mechanical plus relation and framing checks: missing refs, NOT_FACING, SIT_FLOATING, CLIP_THROUGH, AXIS_CROSS, NO_HEADROOM, FOOT_FLOAT, THIRTY_DEGREE.',
    inputSchema: obj({}),
  },
  {
    name: 'scene.snapshot',
    backend: 'live',
    group: 'observe',
    annotations: read,
    description: 'Capture the live viewport as JPEG. Optional Set-of-Mark overlay (ids, facing, grid, contacts). Open the image; a path is not inspection.',
    inputSchema: obj({
      cameraId: { type: 'string' },
      overlay: { type: 'array', items: { type: 'string', enum: ['ids', 'facing', 'grid', 'contacts', 'thirds', 'safe', 'axis'] } },
      atTimes: { type: 'array', items: { type: 'number' } },
      layout: { type: 'string', enum: ['sheet', 'separate'] },
      aspect: { type: ['number', 'string'] },
    }),
  },
  {
    name: 'scene.solve_layout',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Solve named spatial relations (face, sit_on, distance, near, in_front_of, side_of, on_ground) into set_transform ops. Prefer this over raw world coordinates. apply:false returns the plan only.',
    inputSchema: obj({
      description: { type: 'string' },
      edges: { type: 'array', items: { type: 'object' } },
      dsl: { type: 'string' },
      apply: { type: 'boolean' },
    }),
  },
  {
    name: 'scene.coverage',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Build coverage campaths. dialogue/two_shot/singles need two subjects. insert needs one target (prop or character) and places a CU/ECU. Shot scale (ecu–ews) sizes singles; holdS is seconds per hold.',
    inputSchema: obj({
      a: { type: 'string' },
      b: { type: 'string' },
      target: { type: 'string' },
      set: { type: 'string', enum: ['dialogue', 'two_shot', 'singles', 'insert'] },
      scale: { type: 'string', enum: ['ecu', 'cu', 'mcu', 'ms', 'mls', 'ws', 'ews'] },
      holdS: { type: 'number' },
      filmback: { type: 'string', enum: ['35mm', 'super35', '16mm', '16:9'] },
    }),
  },
  {
    name: 'scene.angles',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Park six retake cameras around one subject (Front, Front side, Rear side, Back, Overhead, Low Angle). Subject-relative yaw/pitch, not dialogue coverage. Named lens combo sets filmback+mm. capture:true (default) then scene.snapshot atTimes as one labeled sheet.',
    inputSchema: obj({
      target: { type: 'string' },
      a: { type: 'string' },
      id: { type: 'string' },
      scale: { type: 'string', enum: ['ecu', 'cu', 'mcu', 'ms', 'mls', 'ws', 'ews'] },
      combo: { type: 'string', enum: ['s35-24', 's35-35', 's35-50', 's35-85', 'ff-24', 'ff-50', 'ff-85'] },
      filmback: { type: 'string', enum: ['35mm', 'super35', '16mm', '16:9'] },
      holdS: { type: 'number' },
      capture: { type: 'boolean' },
      validateOnly: { type: 'boolean' },
    }),
  },
  {
    name: 'stage.generate',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Cloud image or video (xAI Imagine). kind=image text-to-still; edit needs a source still; video is text or image-to-video. Optional view/combo/scale append cinema language. snapshot:true grabs the live camera first. 3D mesh generation is not available. Needs XAI_API_KEY on the server.',
    inputSchema: obj({
      kind: { type: 'string', enum: ['image', 'edit', 'video'] },
      prompt: { type: 'string' },
      image: { type: 'string' },
      images: { type: 'array', items: { type: 'string' } },
      view: { type: 'string', enum: ['front', 'front_side', 'rear_side', 'back', 'overhead', 'low_angle'] },
      combo: { type: 'string', enum: ['s35-24', 's35-35', 's35-50', 's35-85', 'ff-24', 'ff-50', 'ff-85'] },
      scale: { type: 'string', enum: ['ecu', 'cu', 'mcu', 'ms', 'mls', 'ws', 'ews'] },
      duration: { type: 'number' },
      aspect: { type: 'string' },
      resolution: { type: 'string' },
      snapshot: { type: 'boolean' },
      cameraId: { type: 'string' },
      apply: { type: 'string', enum: ['none', 'reference'] },
    }, ['prompt']),
  },
  {
    name: 'stage.retake',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Video Retake on this stage: snapshot the live/named camera, then cloud-edit the still or animate it (image-to-video). view is Front / Front side / Rear side / Back / Overhead / Low Angle. kind=image keeps a still; default is video.',
    inputSchema: obj({
      kind: { type: 'string', enum: ['image', 'video'] },
      prompt: { type: 'string' },
      view: { type: 'string', enum: ['front', 'front_side', 'rear_side', 'back', 'overhead', 'low_angle'] },
      combo: { type: 'string' },
      scale: { type: 'string' },
      cameraId: { type: 'string' },
      duration: { type: 'number' },
      aspect: { type: 'string' },
    }),
  },
  {
    name: 'stage.replace',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Object replace: natural-language edit of a still or video. Pass image=/uploads/… or video=/uploads/….mp4. Snapshot first with snapshot:true if you want the current frame.',
    inputSchema: obj({
      prompt: { type: 'string' },
      image: { type: 'string' },
      video: { type: 'string' },
      snapshot: { type: 'boolean' },
      cameraId: { type: 'string' },
    }, ['prompt']),
  },
  {
    name: 'stage.extend',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Continue a generated or imported mp4 from its last frame (视频续写). video is /uploads path or https URL.',
    inputSchema: obj({
      prompt: { type: 'string' },
      video: { type: 'string' },
      duration: { type: 'number' },
    }, ['prompt', 'video']),
  },
  {
    name: 'stage.multicam',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Multicam: list cameras, hard-cut the live view (Blender 1–9 / Cinemachine adjacent clips), 2×2 JPEG preview, and an optional cut list with play. id or 1-based index. 0 returns to director view.',
    inputSchema: obj({
      action: { type: 'string', enum: ['list', 'cut', 'director', 'preview', 'mark', 'clear', 'play', 'pause', 'arm'] },
      id: { type: 'string' },
      index: { type: 'integer', minimum: 1, maximum: 9 },
      ids: { type: 'array', items: { type: 'string' } },
      tMs: { type: 'number' },
      mark: { type: 'boolean' },
      blendMs: { type: 'number' },
      fromMs: { type: 'number' },
      enabled: { type: 'boolean' },
    }, ['action']),
  },
  {
    name: 'stage.contact',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Plant character feet: drop a standing root so ankles meet groundY (default 0), then CCD the hip–knee–ankle chains. Sit/drive keeps hip height. scene.edit plant_feet or sit_on/on_ground layout also triggers this.',
    inputSchema: obj({
      action: { type: 'string', enum: ['plant'] },
      id: { type: 'string' },
      ids: { type: 'array', items: { type: 'string' } },
      groundY: { type: 'number' },
    }),
  },
  {
    name: 'model.generate',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Create or replace a sandboxed procedural Three.js code model. No import/fetch/DOM.',
    inputSchema: obj({
      code: { type: 'string' },
      id: { type: 'string' },
      label: { type: 'string' },
      position: vec3,
    }, ['code']),
  },
  {
    name: 'model.capture',
    backend: 'live',
    group: 'observe',
    annotations: read,
    description: 'Offscreen canonical views of a code model for visual review.',
    inputSchema: obj({
      id: { type: 'string' },
      views: { type: 'array', items: { type: 'string' } },
      layout: { type: 'string', enum: ['grid', 'separate'] },
    }),
  },
  {
    name: 'model.compare',
    backend: 'live',
    group: 'observe',
    annotations: read,
    description: 'Advisory silhouette comparison between a capture and a reference image. Not visual acceptance.',
    inputSchema: obj({
      renderPath: { type: 'string' },
      referencePath: { type: 'string' },
    }, ['renderPath', 'referencePath']),
  },
  {
    name: 'motion.read',
    backend: 'live',
    group: 'dsl',
    annotations: read,
    description: 'Read motion DSL source for a built-in or custom motion id.',
    inputSchema: obj({ id: { type: 'string' } }, ['id']),
  },
  {
    name: 'campath.read',
    backend: 'live',
    group: 'dsl',
    annotations: read,
    description: 'Read camera-path DSL source for an existing path id.',
    inputSchema: obj({ id: { type: 'string' } }, ['id']),
  },
  {
    name: 'stage.export_image',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Trigger Export Image (current camera / director view). Requires the live tab; user sees the download.',
    inputSchema: obj({}),
  },
  {
    name: 'stage.export_video',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Trigger timeline video export. Fails if the timeline has no clips.',
    inputSchema: obj({}),
  },
  {
    name: 'stage.import_asset',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Import a local GLB/GLTF/PLY/SPZ already uploaded under /uploads, or a same-origin url. Returns id and url.',
    inputSchema: obj({
      url: { type: 'string' },
      path: { type: 'string' },
      name: { type: 'string' },
      position: vec3,
    }),
  },
  {
    name: 'stage.place',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Place a character (bodyType mannequin/female/child, pose, heightM) or a primitive/furniture prop (assetId mesh_cube… chair, round_table). Position defaults to origin. One undo batch. The original add-object picker is the UI for characters/props.',
    inputSchema: obj({
      kind: { type: 'string', enum: ['character', 'prop', 'primitive'] },
      bodyType: { type: 'string', enum: ['mannequin', 'female', 'child'] },
      assetId: { type: 'string' },
      pose: { type: 'string' },
      heightM: { type: 'number' },
      label: { type: 'string' },
      position: vec3,
    }),
  },
  {
    name: 'stage.pose',
    backend: 'live',
    group: 'core',
    annotations: write,
    description: 'Set a live character pose (stand/sit/walk/wave/think/bow/kneel/lie/tpose/akimbo/hands_up/squat/drive). id defaults to selection.',
    inputSchema: obj({
      id: { type: 'string' },
      pose: { type: 'string' },
    }, ['pose']),
  },
  {
    name: 'stage.shot',
    backend: 'live',
    group: 'dsl',
    annotations: write,
    description: 'Apply a named 运镜 recipe as set_campath DSL: hero_reveal, tracking, punch_in, hitchcock, orbit_90, rise, whip, follow. target is a character/prop id. The original campath picker already hosts the same preset ids.',
    inputSchema: obj({
      recipe: { type: 'string', enum: ['hero_reveal', 'tracking', 'punch_in', 'hitchcock', 'orbit_90', 'rise', 'whip', 'follow'] },
      target: { type: 'string' },
      id: { type: 'string' },
    }, ['recipe']),
  },
  {
    name: 'stage.focus',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Fly the director camera to frame an object (聚焦 F). Omit id to use current selection.',
    inputSchema: obj({ id: { type: 'string' } }),
  },
  {
    name: 'stage.possess',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Enter first-person control of a character, prop, or imported model. Omit id to use current selection.',
    inputSchema: obj({ id: { type: 'string' }, snapshot: { type: 'boolean' } }),
  },
  {
    name: 'stage.exit_possess',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Leave first-person control and commit the last transform.',
    inputSchema: obj({}),
  },
  {
    name: 'stage.play',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Play, pause, seek, or nudge the camera timeline. No args toggles. seekMs is absolute; nudgeMs is ±ms (J/K = ±1000). Q/E stay viewport up/down.',
    inputSchema: obj({
      playing: { type: 'boolean' },
      seekMs: { type: 'number' },
      nudgeMs: { type: 'number' },
    }),
  },
  {
    name: 'stage.look',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Apply live look: three-point, ACES, DoF, IBL, display LUT, focus plane, peaking, plus studio kelvin/brightness/key slot/rim (打光). Prefer scene.edit set_look.',
    inputSchema: obj({
      rig: { type: 'object' },
      lights: { type: 'array', items: { type: 'object' } },
      remove: { type: 'array', items: { type: 'string' } },
      exposure: { type: 'number' },
      toneMap: { type: 'string', enum: ['aces', 'none'] },
      ambient: { type: 'number' },
      dof: { type: 'boolean' },
      focusM: { type: 'number' },
      aperture: { type: 'number' },
      ibl: { type: 'boolean' },
      iblIntensity: { type: 'number' },
      lut: { type: 'string' },
      lutIntensity: { type: 'number', minimum: 0, maximum: 1 },
      focusPlane: { type: 'boolean' },
      peaking: { type: 'boolean' },
      peakWidth: { type: 'number' },
      lookAt: { type: 'object' },
      kelvin: { type: 'number' },
      brightness: { type: 'number' },
      key: { type: 'string', enum: ['left', 'top', 'right', 'front', 'bottom'] },
      rim: { type: 'number' },
      hdri: { type: 'string' },
      azimuth: { type: 'number' },
    }),
  },
  {
    name: 'stage.viewfinder',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Set the original aspect picker (16:9…2.39:1) and focal length (12–200mm, [ ] nudges 1mm). shoot=scene.snapshot cropped to that gate. Letterbox/thirds stay the original overlay.',
    inputSchema: obj({
      action: { type: 'string', enum: ['open', 'close', 'set', 'shoot', 'status'] },
      aspect: { type: 'string' },
      focalMm: { type: 'number' },
      thirds: { type: 'boolean' },
    }),
  },
  {
    name: 'stage.environment',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Environment extras on top of the original inspector: site blank/room (room walls), named lighting look (柔光影棚…夜间街道), azimuth. Ground height/grid/background/top view use the original env panel and axis gizmo. 3D mesh gen is out of scope.',
    inputSchema: obj({
      site: { type: 'string', enum: ['blank', 'room'] },
      groundHeight: { type: 'number' },
      groundSize: { type: 'number' },
      grid: { type: 'boolean' },
      hdri: { type: 'string' },
      azimuth: { type: 'number' },
      background: { type: 'string', enum: ['none', 'match_lights', 'panorama'] },
      view: { type: 'string', enum: ['3d', 'top'] },
    }),
  },
  {
    name: 'stage.trim',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Trim a generated/imported mp4. Confirm writes a NEW /uploads file and keeps the original. action=probe duration; smart=scene-cut list; trim uses inMs/outMs or inS/outS.',
    inputSchema: obj({
      action: { type: 'string', enum: ['trim', 'probe', 'smart'] },
      path: { type: 'string' },
      video: { type: 'string' },
      inMs: { type: 'number' },
      outMs: { type: 'number' },
      inS: { type: 'number' },
      outS: { type: 'number' },
    }),
  },
  {
    name: 'stage.timeline',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: '3D timeline clips: list, or trim a clip in-place (inMs/outMs relative to the clip). Play remains the original timeline / stage.play.',
    inputSchema: obj({
      action: { type: 'string', enum: ['list', 'open', 'trim'] },
      clipId: { type: 'string' },
      inMs: { type: 'number' },
      outMs: { type: 'number' },
    }, ['action']),
  },
  {
    name: 'stage.capture_frame',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Grab one JPEG from a generated/imported mp4. which=first|last|at (截帧). atMs/atS used when which=at. Writes a NEW /uploads file; original kept.',
    inputSchema: obj({
      path: { type: 'string' },
      video: { type: 'string' },
      which: { type: 'string', enum: ['first', 'last', 'at'] },
      atMs: { type: 'number' },
      atS: { type: 'number' },
    }),
  },
  {
    name: 'stage.playlist',
    backend: 'live',
    group: 'io',
    annotations: world,
    description: 'Hard-cut concat of existing /uploads mp4s (剪辑时间线). action=preview returns the filter graph; concat writes a NEW file and keeps sources. Needs at least two paths.',
    inputSchema: obj({
      action: { type: 'string', enum: ['concat', 'preview'] },
      paths: { type: 'array', items: { type: 'string' } },
    }),
  },
  {
    name: 'stage.handheld',
    backend: 'live',
    group: 'device',
    annotations: write,
    description: 'Runtime handheld noise on the live camera (degrees). 0 disables. Not baked into campath control points.',
    inputSchema: obj({
      amp: { type: 'number', minimum: 0, maximum: 8 },
      hz: { type: 'number' },
    }, ['amp']),
  },
  {
    name: 'stage.vcam',
    backend: 'live',
    group: 'device',
    annotations: world,
    description: 'Virtual camera panel: open, close, status, record, stop. Phone QR lives in the live UI.',
    inputSchema: obj({
      action: { type: 'string', enum: ['open', 'close', 'status', 'record', 'stop'] },
    }, ['action']),
  },
  {
    name: 'stage.take',
    backend: 'live',
    group: 'observe',
    annotations: write,
    description: 'Named scene checkpoints. record copies composition+look+JPEG without mutating the original (Unreal take copies). restore applies that copy. compare overlays two take JPEGs as an A/B wipe. list/get/delete read the local takes folder.',
    inputSchema: obj({
      action: { type: 'string', enum: ['record', 'list', 'get', 'restore', 'delete', 'compare'] },
      id: { type: 'string' },
      label: { type: 'string' },
      a: { type: 'string' },
      b: { type: 'string' },
      mode: { type: 'string', enum: ['wipe', 'overlay'] },
    }, ['action']),
  },
  {
    name: 'stage.onion',
    backend: 'live',
    group: 'observe',
    annotations: write,
    description: 'Screen-space onion skin or A/B wipe over the live viewport. Before ghosts tint cool, after ghosts tint warm (Blender GP Before/After). Pass JPEG paths or take ids; not 3D mesh ghosts.',
    inputSchema: obj({
      enabled: { type: 'boolean' },
      mode: { type: 'string', enum: ['overlay', 'wipe'] },
      opacity: { type: 'number', minimum: 0, maximum: 1 },
      wipe: { type: 'number', minimum: 0, maximum: 1 },
      before: { type: 'string' },
      after: { type: 'string' },
    }),
  },
  {
    name: 'director_get_state',
    backend: 'project',
    group: 'project',
    annotations: read,
    description: 'Read the file-backed previs project (no browser). Default compact; detail=full includes catalog and full project JSON.',
    inputSchema: obj({ detail: { type: 'string', enum: ['compact', 'full'] } }),
  },
  {
    name: 'director_create_project',
    backend: 'project',
    group: 'project',
    annotations: destroy,
    description: 'Create a clean local previs project with two actors, four shots and a 15-second timeline.',
    inputSchema: obj({ name: { type: 'string' } }),
  },
  {
    name: 'director_select',
    backend: 'project',
    group: 'project',
    annotations: { ...write, idempotentHint: true },
    description: 'Select a shot or seek to an exact integer frame at 24fps.',
    inputSchema: obj({
      shot_id: { type: 'string' },
      frame: { type: 'integer', minimum: 0 },
    }),
  },
  {
    name: 'director_add_element',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Add an actor or greybox prop to the file-backed project.',
    inputSchema: obj({
      kind: { type: 'string' },
      preset: { type: 'string' },
      name: { type: 'string' },
      position: vec3,
    }),
  },
  {
    name: 'director_update_element',
    backend: 'project',
    group: 'project',
    annotations: { ...write, idempotentHint: true },
    description: 'Move, rotate, scale, rename or recolour a file-backed element. Sugar over a single locked mutate.',
    inputSchema: obj({
      element_id: { type: 'string' },
      shot_id: { type: 'string' },
      shot_only: { type: 'boolean' },
      name: { type: 'string' },
      position: vec3,
      rotation_deg: vec3,
      scale: vec3,
      color: { type: 'string' },
      visible: { type: 'boolean' },
    }, ['element_id']),
  },
  {
    name: 'director_apply_action',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Apply a motion template to an exact actor id and generate motion keyframes.',
    inputSchema: obj({
      element_id: { type: 'string' },
      action: { type: 'string' },
      shot_id: { type: 'string' },
      start_frame: { type: 'integer' },
      duration_frames: { type: 'integer' },
    }, ['element_id', 'action']),
  },
  {
    name: 'director_set_motion_keyframe',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Add or edit an actor motion keyframe. Locked work needs override_locked after user confirmation.',
    inputSchema: obj({
      action_id: { type: 'string' },
      frame: { type: 'integer' },
      shot_id: { type: 'string' },
      keyframe_id: { type: 'string' },
      position: vec3,
      override_locked: { type: 'boolean' },
    }, ['action_id', 'frame']),
  },
  {
    name: 'director_apply_camera',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Apply a camera-move template and generate camera keyframes.',
    inputSchema: obj({
      move: { type: 'string' },
      shot_id: { type: 'string' },
      override_locked: { type: 'boolean' },
    }, ['move']),
  },
  {
    name: 'director_set_camera_keyframe',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Add or edit a camera keyframe with exact frame, position, target, fov and roll.',
    inputSchema: obj({
      frame: { type: 'integer' },
      shot_id: { type: 'string' },
      keyframe_id: { type: 'string' },
      position: vec3,
      target: vec3,
      fov: { type: 'number' },
      override_locked: { type: 'boolean' },
    }, ['frame']),
  },
  {
    name: 'director_manage_shot',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Add, duplicate, rename, reorder or delete a shot.',
    inputSchema: obj({
      operation: { type: 'string', enum: ['add', 'duplicate', 'rename', 'reorder', 'delete'] },
      shot_id: { type: 'string' },
      name: { type: 'string' },
      duration_frames: { type: 'integer' },
      index: { type: 'integer' },
    }, ['operation']),
  },
  {
    name: 'director_set_lock',
    backend: 'project',
    group: 'project',
    annotations: { ...write, idempotentHint: true },
    description: 'Lock or unlock a manually approved action or keyframe.',
    inputSchema: obj({
      target: { type: 'string', enum: ['action', 'motion_keyframe', 'camera_keyframe'] },
      id: { type: 'string' },
      shot_id: { type: 'string' },
      locked: { type: 'boolean' },
    }, ['target', 'id']),
  },
  {
    name: 'director_delete',
    backend: 'project',
    group: 'project',
    annotations: destroy,
    description: 'Delete an element, action or keyframe. Locked work needs override_locked.',
    inputSchema: obj({
      target: { type: 'string', enum: ['element', 'action', 'motion_keyframe', 'camera_keyframe'] },
      id: { type: 'string' },
      shot_id: { type: 'string' },
      override_locked: { type: 'boolean' },
    }, ['target', 'id']),
  },
  {
    name: 'director_undo',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Undo one file-backed Director edit (up to 50 snapshots).',
    inputSchema: obj({}),
  },
  {
    name: 'director_redo',
    backend: 'project',
    group: 'project',
    annotations: write,
    description: 'Redo one previously undone file-backed Director edit.',
    inputSchema: obj({}),
  },
  {
    name: 'director_validate',
    backend: 'project',
    group: 'project',
    annotations: read,
    description: 'Inspect the file-backed project for collisions, overlaps and camera issues.',
    inputSchema: obj({}),
  },
];

export const AGENT_TOOL_GROUPS: ToolGroup[] = ['core', 'observe', 'dsl', 'io', 'device', 'project'];

export function findAgentTool(name: string): AgentTool | undefined {
  return AGENT_TOOLS.find((tool) => tool.name === name);
}

export function listAgentTools(group?: string): AgentTool[] {
  if (!group) return AGENT_TOOLS;
  return AGENT_TOOLS.filter((tool) => tool.group === group);
}

export const AGENT_PROMPTS = [
  {
    name: 'director_loop',
    description: 'Mandatory observe → edit → look loop for the live stage.',
    text: [
      '1. scene.get for exact ids (not visual evidence).',
      '2. scene.diagnostics; fix error-level issues first.',
      '3. Prefer scene.solve_layout / set_relations over raw world coordinates. Dialogue coverage: scene.coverage. Lenses: set_camera focalLengthMm, not raw fov.',
      '4. scene.edit validateOnly:true, then the same batch without validateOnly. One user intent = one batch. Dialogue cameras: scene.coverage then stage.multicam preview/cut. One-subject retakes (Front/Front side/Rear side/Back/Overhead/Low Angle): scene.angles, not five OTS paths. Cloud stills/clips: stage.generate / stage.retake / stage.replace / stage.extend (XAI_API_KEY). Do not generate 3D meshes. Prop/hands CU: scene.coverage set insert. Lenses: from scale mcu or set_lens_combo s35-50, not raw fov. Camera language: zoom/pan/tilt/jib/dolly-zoom/roll in set_campath; add_campath presets include pan/tilt/zoom_in/jib_up/whip/follow.',
      '5. scene.snapshot (overlay ids if grounding is unclear). Open the JPEG. Named checkpoints: stage.take record/restore; onion/wipe via stage.onion or stage.take compare. Exposure readability: set_look lut falsecolor; focus: focusPlane + focusM.',
      '6. Timeline changes: snapshot atTimes as a sheet; suspicious beats with layout:separate.',
      '7. Do not eval arbitrary JS. Do not claim visual completion from diagnostics.clean or IoU.',
      '8. Do not override locks or export without the user confirming.',
    ].join('\n'),
  },
];
